_target_: pytorch_lightning.Trainer

# set `1` to train on GPU, `0` to train on CPU only
gpus: 1

min_epochs: 1
max_epochs: 14

weights_summary: null
progress_bar_refresh_rate: 10
log_gpu_memory: True
val_check_interval: 0.5
# resume_from_checkpoint: null
# accelerator: ddp_spawn
