_target_: src.datamodules.dsl_datamodule.DSLDataModule

data_dir: ${data_dir} # data_dir is specified in config.yaml
batch_size: 16
num_workers: 16
pin_memory: False
downsampeling: 0
dataset_size: 0
channels: ugriz